name: Publish to GitHub Packages

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: "@thisguymartin"
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install # Equivalent to npm ci in pnpm
      - run: pnpm build # Equivalent to npm ci in pnpm
      - run: pnpm test
      - run: npm run build # if you have a build script
      - name: Publish to GitHub Packages
        run:  pnpm -r publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.BAREBONE_GITHUB_SECRET }}

