# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package with pnpm

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm' # Enable caching for pnpm
      - run: npm install -g pnpm # Install pnpm globally
      - run: pnpm install # Equivalent to npm ci in pnpm
      - run: pnpm build # Equivalent to npm ci in pnpm
      - run: pnpm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm' # Enable caching for pnpm
      - run: npm install -g pnpm # Install pnpm globally
      - run: pnpm install # Install dependencies using pnpm
      - run: pnpm publish # Publish using pnpm
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
